### ISSUE TITLE
README.MD full suite wrong link in all projects

### ISSUE THREAD

**Issue by benni347** [FossifyOrg/Calculator#1]
**Checklist**
[ ] I can reproduce the bug with the latest version. 
[ x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.

**Describe the bug**
In all repos FossifyX is still linked in the readme and in the issue template too. Would recommend updating it to FossifyOrg

**Comment by Aga-C** [comment]
This will be fixed soon, don't worry.

BTW. Please raise issues regarding all projects in https://github.com/FossifyOrg/General-Discussion/issues.
