### ISSUE TITLE
Themed Icon Doesn't Match Regular Icon

### ISSUE THREAD

**Issue by randomtestaccount321** [FossifyOrg/Calculator#23]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calculator/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calculator/issues) or [closed](https://github.com/FossifyOrg/Calculator/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calculator/discussions) or [closed](https://github.com/FossifyOrg/Calculator/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calculator/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Motorola Moto G53

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

On the android emulator on android studio using android 14 / 15 with the default Google Pixel launcher, you can long press on an empty part of the home screen, click "Wallpaper & style", then scroll down, turn on "Themed icons" and look at the Fossify Calculator icon

### Expected behavior

The icon looks like the Fossify Calculator icon but monochrome with the system accent colour

### Actual behavior

The icon looks like the Simple Mobile Tools Calculator icon but monochrome with the system accent colour

### Screenshots/Screen recordings

Regular icons: https://github.com/user-attachments/assets/b92d92bb-551f-46e5-ab50-70e8640eb342
Themed icons: https://github.com/user-attachments/assets/df18ffc4-613c-4e3c-9c49-500a8d8dfafc

**Comment by naveensingh** [comment]
Should be fixed in the next update.
