### ISSUE TITLE
Where is "convert currencies"?

### ISSUE THREAD

**Issue by M1CK431** [FossifyOrg/Calculator#26]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calculator/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calculator/issues) or [closed](https://github.com/FossifyOrg/Calculator/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calculator/discussions) or [closed](https://github.com/FossifyOrg/Calculator/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calculator/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 14 / iodéOS 5.5-20240917-akatsuki

### Affected device model

Sony Xperia XZ3

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Open the app, tap on the "conversion" btn (top right)

### Expected behavior

Should find a "Currencies" conversion along length, surface, volume, temperature, time, etc...

### Actual behavior

no entries for currencies conversion...

### Screenshots/Screen recordings

<img alt="image" src="https://github.com/user-attachments/assets/485d0f23-c2ca-4e7e-a006-238e47a9a807" width=200 />

### Additional information

NB: It's not a feature request because the README of this project stand:
> Whether you need to multiply, divide, calculate roots and powers, **or convert currencies**, Fossify Calculator has got you covered. It's perfect for everyday calculations and more specialized tasks like mortgage calculations.

**Comment by Aga-C** [comment]
Actually, that's a bug, but in README. Fossify Calculator will never have currency converter, because it would require an Internet access, and the app don't have it by design. We will change that text in README to not mislead anyone.

**Comment by M1CK431** [comment]
Thanks for the clarification. However, I think this issue should be closed only when the README will be updated (+ linked to the related PR). This way, anyone with the same question will find the answer easier 😉
