### ISSUE TITLE
Release this on the Google Play Store

### ISSUE THREAD

**Issue by MysteriousOrb2000** [FossifyOrg/Calculator#34]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calculator/issues) or [closed](https://github.com/FossifyOrg/Calculator/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calculator/discussions) or [closed](https://github.com/FossifyOrg/Calculator/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calculator/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

The calcualtor app should be available on the Google play Store.

### Why do you want this feature?

This would make this project more available to people.

**Comment by Aga-C** [comment]
See: https://github.com/orgs/FossifyOrg/discussions/57#discussioncomment-11059627.
